#!/bin/bash
set -eo pipefail

# ============================================================
# Build Trust Wallet Core native libraries for ceres_wallet_core
# ============================================================
#
# Usage:
#   ./tool/build_native.sh [ios|android|all]
#
# Produces:
#   ios/Libraries/libCeresWalletCore.a      (merged: C++ + protobuf + trezor-crypto + Rust)
#   android/src/main/jniLibs/{ABI}/*.so     (stripped)
#
# Requirements:
#   - macOS (for iOS builds)
#   - CMake, Ninja, Python 3
#   - Rust nightly with targets: aarch64-apple-ios, aarch64-apple-ios-sim,
#     aarch64-linux-android, armv7-linux-androideabi, x86_64-linux-android
#   - Android NDK (for Android builds)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(dirname "$SCRIPT_DIR")"
WC_DIR="$PLUGIN_DIR/third_party/wallet-core"
TARGET="${1:-all}"

echo "=== Ceres Wallet Core Native Build ==="
echo "Target: $TARGET"
echo ""

# ---- Step 1: Init submodule ----
if [ ! -f "$WC_DIR/CMakeLists.txt" ]; then
    echo ">>> Initializing wallet-core submodule..."
    (cd "$PLUGIN_DIR" && git submodule update --init --depth 1 third_party/wallet-core)
fi
echo ">>> wallet-core: $(cd "$WC_DIR" && git describe --tags --always)"
# Reset any local changes from previous build
(cd "$WC_DIR" && git checkout -- .)

cd "$WC_DIR"

# ---- Step 2: Install deps + generate files ----
# Don't run full bootstrap.sh — it downloads lcov/sys-deps which timeout on CI.
# CI workflow already installs cmake/ninja/protobuf/boost via apt/brew.
echo ">>> Installing C++ dependencies..."
bash tools/install-dependencies 2>&1

echo ">>> Installing Rust dependencies..."
bash tools/install-rust-dependencies dev 2>&1 || echo "  (partial — continuing)"

echo ">>> Generating files..."
bash tools/generate-files native 2>&1 || echo "  (partial — continuing)"

# ---- Step 3: Trim registry ----
echo ">>> Trimming registry..."
python3 "$SCRIPT_DIR/trim_registry.py" "$WC_DIR"

# ---- Step 4: Apply patches ----
echo ">>> Applying CI patches..."
rm -rf "$WC_DIR/_trimmed_src" "$WC_DIR/rust/_trimmed_chains"
python3 "$SCRIPT_DIR/ci_patches.py" "$WC_DIR"

# ---- Step 5: Build Rust + generate bindgen header ----
echo ">>> Building Rust (host)..."
(cd "$WC_DIR/rust" && cargo build --release 2>&1 | tail -1)
echo ">>> Generating cbindgen header..."
mkdir -p "$WC_DIR/src/rust/bindgen"
(cd "$WC_DIR/rust" && cbindgen --crate wallet-core-rs --output ../src/rust/bindgen/WalletCoreRSBindgen.h 2>&1 | tail -1)

# ---- Step 6b: Run codegen-v2 for C++ headers ----
echo ">>> Running codegen-v2..."
(cd "$WC_DIR/codegen-v2" && cargo run -- cpp 2>&1 | tail -1)

# Protobuf C++ headers are generated by bootstrap's generate-files
# using wallet-core's bundled protoc (matching protobuf 3.20.3).
# Do NOT regenerate with system protoc — causes version mismatch.

# Remove generated files for trimmed chains
rm -f "$WC_DIR"/src/Generated/TWTONAddressConverter.cpp \
      "$WC_DIR"/src/Generated/TWTONMessageSigner.cpp \
      "$WC_DIR"/src/Generated/TWTONWallet.cpp \
      "$WC_DIR"/src/Generated/TWBiz.cpp \
      "$WC_DIR"/src/Generated/TWSolanaTransaction.cpp

echo ""
echo "=== Source ready. Building targets... ==="
echo ""

# ---- iOS Build ----
build_ios() {
    echo ">>> Building iOS..."

    FW_NAME="ceres_wallet_core"
    FW_DIR="$PLUGIN_DIR/ios/Frameworks"
    BUNDLE_ID="com.ceresecosystem.cereswalletcore"
    FW_VERSION="1.0"

    # Build Rust for iOS
    echo "  Rust: aarch64-apple-ios"
    (cd "$WC_DIR/rust" && cargo build --release --target aarch64-apple-ios)
    echo "  Rust: aarch64-apple-ios-sim"
    (cd "$WC_DIR/rust" && cargo build --release --target aarch64-apple-ios-sim)

    # Build C++ for simulator
    echo "  C++: iOS simulator (arm64)"
    rm -rf "$WC_DIR/build/ios-sim"
    cmake -S "$WC_DIR" -B "$WC_DIR/build/ios-sim" -G Ninja -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64 \
        -DCMAKE_OSX_SYSROOT=iphonesimulator -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0 \
        -DFLUTTER=ON -DTW_UNITY_BUILD=ON -DTW_COMPILE_JAVA=OFF -DTW_COMPILE_KOTLIN=OFF
    cmake --build "$WC_DIR/build/ios-sim" --config Release -- TrustWalletCore protobuf TrezorCrypto

    # Build C++ for device
    echo "  C++: iOS device (arm64)"
    rm -rf "$WC_DIR/build/ios-device"
    cmake -S "$WC_DIR" -B "$WC_DIR/build/ios-device" -G Ninja -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64 \
        -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0 \
        -DFLUTTER=ON -DTW_UNITY_BUILD=ON -DTW_COMPILE_JAVA=OFF -DTW_COMPILE_KOTLIN=OFF
    cmake --build "$WC_DIR/build/ios-device" --config Release -- TrustWalletCore protobuf TrezorCrypto

    # Merge all static libs into one fat archive per platform
    echo "  Merging iOS sim libs..."
    libtool -static -o /tmp/libCeresWalletCore_sim.a \
        "$WC_DIR/build/ios-sim/libTrustWalletCore.a" \
        "$WC_DIR/build/ios-sim/libprotobuf.a" \
        "$WC_DIR/build/ios-sim/trezor-crypto/libTrezorCrypto.a" \
        "$WC_DIR/rust/target/aarch64-apple-ios-sim/release/libwallet_core_rs.a"

    echo "  Merging iOS device libs..."
    libtool -static -o /tmp/libCeresWalletCore_device.a \
        "$WC_DIR/build/ios-device/libTrustWalletCore.a" \
        "$WC_DIR/build/ios-device/libprotobuf.a" \
        "$WC_DIR/build/ios-device/trezor-crypto/libTrezorCrypto.a" \
        "$WC_DIR/rust/target/aarch64-apple-ios/release/libwallet_core_rs.a"

    # Write a minimal Info.plist for a framework slice
    # Usage: _write_plist <path> <supported-platform>
    _write_plist() {
        cat > "$1" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>${FW_NAME}</string>
    <key>CFBundleIdentifier</key>
    <string>${BUNDLE_ID}</string>
    <key>CFBundleName</key>
    <string>${FW_NAME}</string>
    <key>CFBundlePackageType</key>
    <string>FMWK</string>
    <key>CFBundleShortVersionString</key>
    <string>${FW_VERSION}</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>MinimumOSVersion</key>
    <string>13.0</string>
    <key>CFBundleSupportedPlatforms</key>
    <array>
        <string>${2}</string>
    </array>
</dict>
</plist>
PLIST
    }

    # Create device .framework (this is the primary artifact for the native assets hook)
    echo "  Creating iOS device .framework..."
    DEV_FW="$FW_DIR/$FW_NAME.framework"
    rm -rf "$DEV_FW"
    mkdir -p "$DEV_FW"
    _write_plist "$DEV_FW/Info.plist" "iPhoneOS"
    clang -dynamiclib \
        -arch arm64 \
        -isysroot "$(xcrun --sdk iphoneos --show-sdk-path)" \
        -mios-version-min=13.0 \
        -install_name "@rpath/$FW_NAME.framework/$FW_NAME" \
        -Wl,-force_load,/tmp/libCeresWalletCore_device.a \
        -lc++ -lz -framework Security -framework Foundation \
        -o "$DEV_FW/$FW_NAME"

    # Create simulator .framework in a temp dir for XCFramework packaging
    echo "  Creating iOS simulator .framework..."
    SIM_FW="/tmp/${FW_NAME}_sim.framework"
    rm -rf "$SIM_FW"
    mkdir -p "$SIM_FW"
    _write_plist "$SIM_FW/Info.plist" "iPhoneSimulator"
    clang -dynamiclib \
        -arch arm64 \
        -isysroot "$(xcrun --sdk iphonesimulator --show-sdk-path)" \
        -mios-simulator-version-min=13.0 \
        -install_name "@rpath/$FW_NAME.framework/$FW_NAME" \
        -Wl,-force_load,/tmp/libCeresWalletCore_sim.a \
        -lc++ -lz -framework Security -framework Foundation \
        -o "$SIM_FW/$FW_NAME"

    # Combine into XCFramework (device + simulator) for CocoaPods/podspec distribution
    echo "  Creating XCFramework..."
    XCF_DIR="$FW_DIR/$FW_NAME.xcframework"
    rm -rf "$XCF_DIR"
    xcodebuild -create-xcframework \
        -framework "$DEV_FW" \
        -framework "$SIM_FW" \
        -output "$XCF_DIR"

    # Cleanup temp files
    rm -f /tmp/libCeresWalletCore_*.a
    rm -rf "$SIM_FW"

    DEV_SIZE=$(du -h "$DEV_FW/$FW_NAME" | cut -f1)
    XCF_SIZE=$(du -sh "$XCF_DIR" | cut -f1)
    echo "  Device framework binary: $DEV_SIZE"
    echo "  XCFramework total: $XCF_SIZE"
    echo ">>> iOS done"
}

# ---- Android Build ----
build_android() {
    echo ">>> Building Android..."

    # Find NDK
    if [ -z "${ANDROID_NDK:-}" ]; then
        for d in "$HOME/Library/Android/sdk/ndk/"*; do
            if [ -f "$d/build/cmake/android.toolchain.cmake" ]; then
                ANDROID_NDK="$d"
            fi
        done
    fi
    if [ -z "${ANDROID_NDK:-}" ]; then
        echo "ERROR: ANDROID_NDK not found"
        exit 1
    fi
    echo "  NDK: $ANDROID_NDK"

    # NDK prebuilt dir — always x86_64 on macOS even on Apple Silicon
    NDK_HOST=$(ls "$ANDROID_NDK/toolchains/llvm/prebuilt/" | head -1)
    NDK_BIN="$ANDROID_NDK/toolchains/llvm/prebuilt/$NDK_HOST/bin"

    # Build Rust for Android
    for TARGET in aarch64-linux-android armv7-linux-androideabi x86_64-linux-android; do
        echo "  Rust: $TARGET"
        case "$TARGET" in
            aarch64-linux-android)
                export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="$NDK_BIN/aarch64-linux-android21-clang"
                export CC_aarch64_linux_android="$NDK_BIN/aarch64-linux-android21-clang"
                export AR_aarch64_linux_android="$NDK_BIN/llvm-ar" ;;
            armv7-linux-androideabi)
                export CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER="$NDK_BIN/armv7a-linux-androideabi21-clang"
                export CC_armv7_linux_androideabi="$NDK_BIN/armv7a-linux-androideabi21-clang"
                export AR_armv7_linux_androideabi="$NDK_BIN/llvm-ar" ;;
            x86_64-linux-android)
                export CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER="$NDK_BIN/x86_64-linux-android21-clang"
                export CC_x86_64_linux_android="$NDK_BIN/x86_64-linux-android21-clang"
                export AR_x86_64_linux_android="$NDK_BIN/llvm-ar" ;;
        esac
        (cd "$WC_DIR/rust" && cargo build --release --target "$TARGET" 2>&1 | tail -1)
    done

    # Build C++ for each ABI
    for ABI in arm64-v8a armeabi-v7a x86_64; do
        echo "  C++: Android $ABI"
        rm -rf "$WC_DIR/build/android-$ABI"
        # Boost is header-only; find it and inject into compiler flags
        # NDK cross-compile sysroot doesn't include host headers
        BOOST_INC="${WC_DIR}/build/local/include"
        if [ ! -d "$BOOST_INC/boost" ]; then
            echo "ERROR: Boost headers not found at $BOOST_INC/boost"
            echo "Run 'bash tools/install-dependencies' in wallet-core first,"
            echo "or 'sudo apt-get install libboost-dev' + symlink to build/local/include/"
            exit 1
        fi
        cmake -S "$WC_DIR" -B "$WC_DIR/build/android-$ABI" -G Ninja -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI="$ABI" -DANDROID_PLATFORM=android-21 \
            -DFLUTTER=ON -DTW_UNITY_BUILD=ON -DTW_COMPILE_JAVA=OFF -DTW_COMPILE_KOTLIN=OFF \
            -DBoost_INCLUDE_DIR="$BOOST_INC" \
            -DCMAKE_CXX_FLAGS="-isystem $BOOST_INC"
        cmake --build "$WC_DIR/build/android-$ABI" --config Release -- TrustWalletCore

        JNILIBS="$PLUGIN_DIR/android/src/main/jniLibs/$ABI"
        mkdir -p "$JNILIBS"
        cp "$WC_DIR/build/android-$ABI/libTrustWalletCore.so" "$JNILIBS/libceres_wallet_core.so"
        "$NDK_BIN/llvm-strip" "$JNILIBS/libceres_wallet_core.so"
        echo "  $ABI: $(du -h "$JNILIBS/libceres_wallet_core.so" | cut -f1) (stripped)"
    done

    echo ">>> Android done"
}

# ---- Package for release ----
package() {
    echo ">>> Packaging..."
    DIST="$PLUGIN_DIR/dist"
    mkdir -p "$DIST"

    FW_NAME="ceres_wallet_core"
    FW_DIR="$PLUGIN_DIR/ios/Frameworks"

    # Package device .framework for native assets hook (hook/build.dart downloads ios-arm64.tar.gz
    # and expects ceres_wallet_core.framework/ceres_wallet_core inside)
    if [ -f "$FW_DIR/$FW_NAME.framework/$FW_NAME" ]; then
        (cd "$FW_DIR" && tar -czf "$DIST/ios-arm64.tar.gz" "$FW_NAME.framework")
        echo "  ios-arm64.tar.gz: $(du -h "$DIST/ios-arm64.tar.gz" | cut -f1)"
    fi

    # Package XCFramework for CocoaPods / podspec distribution (device + simulator slices)
    if [ -d "$FW_DIR/$FW_NAME.xcframework" ]; then
        (cd "$FW_DIR" && tar -czf "$DIST/ios-xcframework.tar.gz" "$FW_NAME.xcframework")
        echo "  ios-xcframework.tar.gz: $(du -h "$DIST/ios-xcframework.tar.gz" | cut -f1)"
    fi

    if [ -d "$PLUGIN_DIR/android/src/main/jniLibs" ]; then
        for ABI in arm64-v8a armeabi-v7a x86_64; do
            SO="$PLUGIN_DIR/android/src/main/jniLibs/$ABI/libceres_wallet_core.so"
            if [ -f "$SO" ]; then
                (cd "$PLUGIN_DIR/android/src/main/jniLibs/$ABI" && tar -czf "$DIST/android-$ABI.tar.gz" libceres_wallet_core.so)
                echo "  android-$ABI.tar.gz: $(du -h "$DIST/android-$ABI.tar.gz" | cut -f1)"
            fi
        done
    fi

    echo ">>> Packaging done"
}

# ---- Execute ----
case "$TARGET" in
    ios)     build_ios; package ;;
    android) build_android; package ;;
    all)     build_ios; build_android; package ;;
    package) package ;;
    *)       echo "Usage: $0 [ios|android|all|package]"; exit 1 ;;
esac

echo ""
echo "=== Build Complete ==="
